export APT_VERSION=6.0

##-----------------------------------------------------------------------
# Configuration Block

export DEB_NAME=iwphys-idship-visual-delivery-play

#export GFY_FLAVOR="sbt assembly"
export GFY_FLAVOR="activator dist"

# export APT_SSH_HOST=apt@apt.identityship.com

##-----------------------------------------------------------------------
# Advanced Options Most users don't need to know about
# Option to speed up for development
#export SBT_VERSION_OVERRIDE=1.1

# Option to skip over sbt/activator clean test
export SKIP_CLEAN_TEST=false

